package kr.sejong.coinwidget;
import android.content.Context;
import android.graphics.Bitmap;
import org.json.*;
import java.util.*;
final class DetailContent {
 static final class Result {String title,price="",text;Bitmap chart;Result(String title,String text){this.title=title;this.text=text;}}
 static final String GUIDE="추천·관심의 목적\n9시 이후 장중에 살 만한 상승 조건 후보를 찾습니다. 상승 추세, BTC 대비 강도, 최근 15분 상승·거래대금 증가를 함께 검사합니다. 조건 미달은 추천에 채우지 않습니다.\n\n중장기 목록의 목적\n1~3개월 관점에서 완료 일봉 20·60·120일 상승 추세, 30일 BTC 대비 강도, 7일 거래대금 증가를 확인합니다. 프로젝트 가치·토큰 발행·뉴스는 반영하지 않은 기술적 선별입니다.\n\n09시 전 목록의 목적\n9시 전에 매수하고 9시 직후 급등 시 매도를 검토할 후보입니다. 08~09시에 최신 자료로 검토하고, 그 밖의 시간은 다음 9시의 예비 목록입니다. 09시가 지나면 해당 목록은 진입 추천을 마칩니다.\n\n9시는 거래 재개가 아닙니다\n업비트는 계속 거래됩니다. 한국시간 09시에 전일 대비 기준이 바뀌는 것이며 급등을 보장하는 신호가 아닙니다. 9시 급등 확률·예상 수익률을 계산한 모델은 아닙니다.\n\n추천을 읽는 순서\n① 새로고침 ② 시장 방어 여부 ③ 종목 누르기 ④ 이유·검토 가격대·무효 조건 확인. 목록은 조회 후 5분까지만 유효합니다. 종목을 누를 때도 다시 검사합니다.\n\n숫자 읽는 법\n단기는 완료 5분봉으로 계산한 최근 15분 등락입니다. 거래 배율은 최근 완료 15분 평균 거래대금을 그 이전 60분 평균과 비교한 값입니다. BTC보다 +1%p 강하다는 것은 같은 6시간 등락 차이입니다.\n\n조건점수는 확률이 아닙니다\n83점은 83% 상승 확률이 아닙니다. 조건을 얼마나 잘 충족했는지 정렬하는 값입니다. 실전 수익성 백테스트, 뉴스, 호가·스프레드 검사는 포함하지 않았습니다.\n\n가격대 읽는 법\n검토 구간은 20시간 평균 주변의 눌림 범위입니다. 도달했다고 바로 사는 신호가 아니며 지지·거래대금을 재확인합니다. 저점 이탈, 추세·거래량 소멸은 추천 무효입니다. 과거 고점은 매도 검토 참고값이고 체결 보장은 없습니다.\n\n데이터와 시간\n업비트 원화 시세·완료 봉, CoinPaprika 또는 설정한 CoinGecko의 비중, ECB 기준 환율을 씁니다. 가격은 조회 시점의 체결가이며 호가가 아닙니다. 15분 자동과 08:30·08:50 예약은 절전·네트워크로 늦을 수 있습니다.\n\n위젯 조작\n상단 금일 추천·09시 전·중장기로 전환합니다. 시장 버튼은 시장 화면을 엽니다. 종목·차트·설명은 위젯 안에서 열립니다. 이전·다음은 설명 페이지 이동, 가운데 목록으로는 돌아가기입니다. 갱신 설정에서 자동 조회를 켜고 끕니다. 앱은 홈 화면의 앱 아이콘으로 엽니다.";
 static Result forScreen(Context c,int id,int screen,JSONObject root,int mode,long now){
  JSONObject m=Renderer.obj(root,"market"),dom=Renderer.obj(root,"dominance"),t=Renderer.obj(m,"btc_technical");
  if(screen==Dashboard.HELP)return new Result("위젯 읽는 법",GUIDE);
  if(screen==Dashboard.SETTINGS)return new Result("갱신 설정","자동 조회: 15분 주기\n9시 전 추가 조회: 08:30·08:50 KST\n\n예약 시각은 안드로이드 절전·통신 상태에 따라 늦어질 수 있습니다. 매수 전 새로고침을 눌러 최신 결과를 확인하세요.\n\n추천 유효시간은 5분입니다. 데이터가 오래되거나 통신에 실패하면 매수 검토를 보류합니다.\n\n기본 데이터 조회는 API 키 없이 작동합니다. 선택적인 외부 API 키 변경은 앱 아이콘으로 연 설정에서 가능합니다.");
  if(screen==Dashboard.BTC){Result d=new Result("BTC 일봉 확대","일봉 · 금색 20일 / 청록 60일 평균\n마지막 일봉은 진행 중일 수 있습니다. RSI·추세 분석은 완료 봉만 사용합니다.");d.price=Charts.number(Renderer.obj(m,"btc").optDouble("price"))+"원";d.chart=MiniCharts.btc(Renderer.arr(m,"daily"));return d;}
  if(screen==Dashboard.DOM){
   double delta=dom.optDouble("delta24",Double.NaN);boolean fresh=!root.optBoolean("dom_failed")&&dom.optLong("time")>0&&now-dom.optLong("time")<=3*Signals.HOUR&&now>=dom.optLong("time")-60000;
   Result d=new Result("비트코인 비중 분석",dom.optString("source","자료 없음")+" · "+Charts.date(dom.optLong("time"),"MM/dd HH:mm")+" KST"+(fresh?"":" · 이전 자료")+"\n"+(Signals.finite(delta)?String.format(Locale.KOREA,"약 24시간 %+.2f%%p",delta):"24시간 전 실측 자료 수집 중")+"\n비중 변화는 자금 유입량이나 상승 확률이 아닙니다.");
   d.price=dom.has("value")?String.format(Locale.KOREA,"BTC %.2f%%",dom.optDouble("value")):"비중 조회 전";d.chart=Charts.dominance(Renderer.arr(dom,"history"));return d;
  }
  String code=Dashboard.prefs(c).getString("coin"+id,"");JSONArray list=Dashboard.list(m,mode);JSONObject a=null;
  for(int i=0;i<list.length();i++)if(code.equals(Renderer.obj(list.optJSONObject(i),"quote").optString("market"))){a=list.optJSONObject(i);break;}
  if(!Dashboard.freshRecommendation(root,mode,now)||a==null)return new Result("매수 검토 보류","이 종목의 추천이 만료되었거나 최신 조건에서 제외됐습니다.\n\n새로고침 후 목록에서 다시 선택하세요. 이전 가격대를 현재 추천으로 사용하지 않습니다.");
  JSONObject q=Renderer.obj(a,"quote");Result d=new Result(q.optString("name")+" ("+code.replace("KRW-","")+")","");d.price=Charts.number(q.optDouble("price"))+"원  "+Charts.pct(q.optDouble("day_pct"));
  if(mode==2){
   d.text="중장기 · 1~3개월 검토\n조건점수 "+Math.round(a.optDouble("score"))+"/100\n\n왜 선정했나요?\n현재가 > 20일 평균 > 60일 평균 > 120일 평균이며 60일 평균도 상승 중입니다.\n30일 "+Charts.pct(a.optDouble("return30"))+" · BTC보다 "+Dashboard.f(a.optDouble("relative30"))+"%p 강함\n최근 7일 평균 거래대금은 그 이전 21일 평균의 "+Dashboard.f(a.optDouble("volume_ratio"))+"배\n\n매수 검토 가격대\n"+Charts.number(a.optDouble("entry_low"))+" ~ "+Charts.number(a.optDouble("entry_high"))+"원\n20일 평균 주변의 눌림 참고 구간입니다. 도달 후 지지와 거래대금 유지 여부를 다시 확인하세요. 현재가 즉시 매수 신호는 아닙니다.\n\n상승 시 참고 저항\n최근 60일 고점 "+Charts.number(a.optDouble("resistance"))+"원\n미래 목표가나 수익 보장이 아닙니다.\n\n추천 무효 조건\n최근 20일 저점 "+Charts.number(a.optDouble("support"))+"원 이탈 또는 20·60·120일 추세 조건 소멸. 시장 악화·뉴스·토큰 발행 일정도 별도로 확인해야 합니다.\n\n추가 수치\nRSI "+Dashboard.f(a.optDouble("rsi"))+" · 일봉 ATR "+Dashboard.f(a.optDouble("atr_pct"))+"%\n20일 평균 "+Charts.number(a.optDouble("ma20"))+"원\n60일 평균 "+Charts.number(a.optDouble("ma60"))+"원\n120일 평균 "+Charts.number(a.optDouble("ma120"))+"원\n\n자료 시각\n최종 체결 "+Charts.date(q.optLong("time"),"MM/dd HH:mm:ss")+" KST\n분석 유효 ~ "+Charts.date(m.optLong("quote_at")+300000,"HH:mm:ss")+" KST\n\n이 목록은 장기 사업 가치를 평가하지 않습니다. 기술적 조건만으로 향후 상승·수익을 확정할 수 없습니다.";
   return d;
  }
  String phase=mode==1?(BeforeNine.entryWindow(now)?"9시 전 매수 검토":"예비 후보 · 08~09시 재확인"):"장중 매수 검토";
  d.text=phase+" · 조건점수 "+Math.round(a.optDouble(mode==1?"morning_score":"score"))+"/100\n\n왜 선정했나요?\n가격이 20·60시간 평균 위이고 20시간 평균이 상승 중입니다.\n"+a.optString("reason")+"\n최근 15분 "+Charts.pct(a.optDouble("pulse_change",Double.NaN))+" · 직전 60분보다 거래대금 "+Dashboard.f(a.optDouble("pulse_ratio",Double.NaN))+"배\n\n매수 검토 가격대\n"+Charts.number(a.optDouble("entry_low"))+" ~ "+Charts.number(a.optDouble("entry_high"))+"원\n현재가 추격보다 구간 도달 후 지지와 거래대금 유지 확인용입니다. 호가·수수료는 반영하지 않았습니다.\n\n상승 시 매도 검토 참고\n최근 20시간 고점 "+Charts.number(a.optDouble("resistance"))+"원\n보장된 목표가가 아닙니다."+(mode==1?" 09시 이후 급등 시 매도를 검토하는 목적이며 자동 매도하지 않습니다.":"")+"\n\n추천 무효 조건\n최근 12시간 저점 "+Charts.number(a.optDouble("support"))+"원 이탈, 추세·거래대금 조건 소멸, 데이터 만료.\n급락·슬리피지 때문에 이 가격에 매도된다고 보장할 수 없습니다.\n\n추가 수치\nRSI "+Dashboard.f(a.optDouble("rsi"))+" · 시간봉 ATR "+Dashboard.f(a.optDouble("atr_pct"))+"%\n6시간 "+Charts.pct(a.optDouble("return6h"))+" · 12시간 "+Charts.pct(a.optDouble("return12h"))+"\n과거 고점·저점 기준 거리비 "+Dashboard.f(a.optDouble("reference_rr"))+" : 1\n\n자료 시각\n최종 체결 "+Charts.date(q.optLong("time"),"MM/dd HH:mm:ss")+" KST\n단기 봉 종료 "+Charts.date(a.optLong("pulse_through"),"HH:mm")+" KST\n추천 유효 ~ "+Charts.date(Math.min(m.optLong("quote_at")+300000,mode==1?m.optLong("recheck_at"):Long.MAX_VALUE),"HH:mm:ss")+" KST\n\n점수는 확률이 아닙니다. 가격 상승이나 9시 급등을 보장하지 않습니다.";
  return d;
 }
}
